name: medikeep
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  cloud_firestore: ^6.0.3
  cloud_functions: ^6.0.4
  dartz: ^0.10.1
  dio: ^5.9.0
  equatable: ^2.0.7
  firebase_auth: ^6.1.1
  firebase_core: ^4.2.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_local_notifications: ^19.5.0
  flutter_native_splash: ^2.4.7
  flutter_riverpod: ^3.0.3
  flutter_timezone: ^5.0.1
  go_router: ^16.3.0
  google_sign_in: ^6.3.0
  mobile_scanner: ^7.1.3
  shared_preferences: ^2.5.3
  timezone: ^0.10.1
  webview_flutter: ^4.13.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0      
  integration_test:
    sdk: flutter
    
flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  #android: "launcher_icon"
  android: true
  ios: false
  image_path: "assets/icon.png"
  min_sdk_android: 16 # android min sdk min:16, default 21

flutter_native_splash:
  android: true
  ios: false
  web: false
  image: assets/icon.png
  color: "#00799D"
  branding: assets/branding.png
  # dark mode
  # image_dark: "assets/splash.png"
  # color_dark: "#1c1c1c"
  # branding_dark: "assets/branding_dark.png"
  # especific for android 12
  android_12:
    image: "assets/icon.png"
    color: "#00799D"
    branding: "assets/branding.png"
    branding_dark: "assets/branding.png"
